// Run with jsdom installed outside production dependencies:
// BV_JSDOM_PATH=/absolute/path/to/jsdom/lib/api.js node scripts/tests/quiz.dom.mjs
import { build } from 'esbuild'
import { mkdir, rm, readFile } from 'node:fs/promises'
import { fileURLToPath, pathToFileURL } from 'node:url'
import assert from 'node:assert/strict'
const repo=fileURLToPath(new URL('../../',import.meta.url))
const { JSDOM }=await import(process.env.BV_JSDOM_PATH || 'jsdom')
const dom=new JSDOM('<div id="root"></div>',{url:'https://banivyatki.ru/?utm_source=yandex&utm_medium=cpc',pretendToBeVisual:true})
for(const k of ['window','document','sessionStorage','HTMLElement','HTMLInputElement','HTMLDialogElement','Event','MouseEvent','KeyboardEvent'])globalThis[k]=dom.window[k]
globalThis.IS_REACT_ACT_ENVIRONMENT=true
HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','')}
HTMLDialogElement.prototype.close=function(){this.removeAttribute('open')}
const folder=repo+'node_modules/.cache/quiz-dom';await mkdir(folder,{recursive:true})
await build({entryPoints:[repo+'src/components/quiz/QuizSection.jsx'],outfile:folder+'/quiz.mjs',bundle:true,format:'esm',platform:'node',jsx:'automatic',external:['react','react-dom','react/jsx-runtime'],define:{'import.meta.env.DEV':'false','import.meta.env.BASE_URL':'"/"'}})
const {default:React,act}=await import('react')
const {createRoot}=await import('react-dom/client')
const {default:Quiz}=await import(pathToFileURL(folder+'/quiz.mjs'))
const data=await import('../../src/data/quiz.js')
let root,checks=0,payloads=[],resolveRequest;const goals=[]
window.ym=(id,method,goal,params)=>goals.push({goal,params})
globalThis.fetch=async(url,options)=>{payloads.push(JSON.parse(options.body));return new Promise(r=>resolveRequest=r)}
const check=(label,value)=>{assert.ok(value,label);checks++}
const click=async(el)=>{assert.ok(el,'click target exists');await act(async()=>el.dispatchEvent(new MouseEvent('click',{bubbles:true})))}
const dialog=()=>document.querySelector('dialog[open]')
const button=(text,within=document)=>[...within.querySelectorAll('button')].find(e=>e.textContent===text)
const back=()=>click(dialog().querySelector('[aria-label="Предыдущий вопрос"]'))
const stepGoals=()=>goals.filter(g=>g.goal==='quiz_step')
const next=async()=>{const count=stepGoals().length;await click(button('Далее',dialog()));check('one goal per manual transition',stepGoals().length===count+1)}
const pick=async(code)=>click(dialog().querySelector(`input[value="${code}"]`))
const waitNext=(ms=280)=>act(async()=>new Promise(r=>setTimeout(r,ms)))
const mount=async()=>{root=createRoot(document.getElementById('root'));await act(async()=>root.render(React.createElement(React.StrictMode,null,React.createElement(Quiz))))}
const unmount=()=>act(async()=>root.unmount())
const close=()=>click(dialog().querySelector('[aria-label="Закрыть"]'))
const input=async(el,value)=>act(async()=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(el,value);el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}))})
const submit=()=>act(async()=>dialog().querySelector('form').dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})))
try {
 await mount()
 check('no automatic modal or reminder',!dialog()&&!document.querySelector('aside'))
 const launch=button('Начать подбор');launch.focus();await click(launch)
 check('banner opens native dialog and locks body',!!dialog()&&document.body.style.overflow==='hidden')
 check('step1 mandatory hint and no navigation',dialog().textContent.includes('* Обязательный вопрос')&&dialog().textContent.includes('Выберите один вариант')&&!button('Далее',dialog())&&!dialog().querySelector('[aria-label="Предыдущий вопрос"]'))
 check('question panel remains 960',dialog().firstElementChild.classList.contains('max-w-[960px]'))
 check('step1 progress20',dialog().querySelector('progress').value===20)
 await pick('ready');check('selected before advance',dialog().querySelector('[value=ready]').checked)
 await waitNext();check('first answer auto advances once',dialog().textContent.includes('Шаг 2 из 5')&&stepGoals().length===1)
 check('quiz_start only once',goals.filter(e=>e.goal==='quiz_start').length===1)
 await back();check('back preserves selection',dialog().querySelector('[value=ready]').checked)
 await waitNext();check('restored first step never auto advances',dialog().textContent.includes('Шаг 1 из 5')&&stepGoals().length===1)
 await pick('ready');await waitNext();check('same selected first answer advances once',dialog().textContent.includes('Шаг 2 из 5')&&stepGoals().length===2)
 const areaGoals=stepGoals().length
 await pick('compact_35');await waitNext(150);await pick('medium_45');await waitNext(150)
 check('changing a radio restarts the timer',dialog().textContent.includes('Шаг 2 из 5')&&dialog().querySelector('[value=medium_45]').checked&&stepGoals().length===areaGoals)
 await waitNext()
 check('area auto advances with one step goal',dialog().textContent.includes('Шаг 3 из 5')&&stepGoals().length===areaGoals+1)
 check('optional hint and exactly two navigation controls',dialog().textContent.includes('Если затрудняетесь ответить — нажмите «Далее».')&&dialog().querySelectorAll('button').length===3&&!button('Пропустить',dialog())&&!button('Продолжить',dialog())&&!button('Назад',dialog()))
 const arrow=dialog().querySelector('[aria-label="Предыдущий вопрос"]')
 check('back is accessible SVG button',arrow.type==='button'&&!!arrow.querySelector('svg[aria-hidden=true]')&&arrow.textContent==='')
 await back();check('back keeps area answer',dialog().querySelector('[value=medium_45]').checked)
 await waitNext();check('restoring an optional answer does not auto advance',dialog().textContent.includes('Шаг 2 из 5'))
 await pick('medium_45');await waitNext();check('clicking saved optional answer auto advances without skipping',dialog().textContent.includes('Шаг 3 из 5')&&JSON.parse(sessionStorage.getItem(data.QUIZ_STORAGE_KEY)).answers.quiz_area==='medium_45')
 const multiGoals=stepGoals().length
 await pick('year_round');await waitNext(150);await pick('terrace');await waitNext(150)
 check('additional checkbox restarts auto timer',dialog().textContent.includes('Шаг 3 из 5')&&stepGoals().length===multiGoals)
 check('multi selection before auto transition',dialog().querySelectorAll('input:checked').length===2)
 await waitNext();check('multi auto advances once with the full CSV',dialog().textContent.includes('Шаг 4 из 5')&&stepGoals().length===multiGoals+1&&JSON.parse(sessionStorage.getItem(data.QUIZ_STORAGE_KEY)).answers.quiz_features==='year_round,terrace')
 await back();await pick('canopy');await back();await waitNext()
 check('Back cancels pending multi auto transition',dialog().textContent.includes('Шаг 2 из 5'))
 await next()
 await pick('unsure');check('unsure exclusive',dialog().querySelectorAll('input:checked').length===1&&dialog().querySelector('[value=unsure]').checked)
 await pick('outside_firebox');check('normal clears unsure',!dialog().querySelector('[value=unsure]').checked)
 await close();check('close returns focus and restores scroll',!dialog()&&document.activeElement===launch&&document.body.style.overflow==='')
 check('floating shown with plan title and current step',!!button('Продолжить',document.querySelector('aside'))&&document.querySelector('aside').textContent.includes('Продолжить подбор бани')&&document.querySelector('aside').textContent.includes('Вы остановились на шаге 3 из 5'))
 const decorative=document.querySelector('aside img')
 check('reminder reuses decorative 640 WebP',decorative.getAttribute('src').endsWith('podkova-35-plan-640.webp')&&decorative.classList.contains('object-contain')&&decorative.alt===''&&decorative.getAttribute('aria-hidden')==='true'&&!decorative.hasAttribute('srcset'))
 const resumeGoals=stepGoals().length
 const floating=button('Продолжить',document.querySelector('aside'));floating.focus();await click(floating)
 check('resume only opens step3 without advancing or a step goal',dialog().textContent.includes('Шаг 3 из 5')&&dialog().querySelector('[value=outside_firebox]').checked&&stepGoals().length===resumeGoals)
 await close();check('floating opener gets focus',document.activeElement===floating)
 await click(document.querySelector('[aria-label="Свернуть напоминание"]'))
 check('compact pill',!!button('Подобрать баню')&&!button('Продолжить',document.querySelector('aside')))
 await unmount();await mount();check('storage restores compact widget',!!button('Подобрать баню'))
 const compact=button('Подобрать баню');compact.focus();await click(compact)
 check('storage restores answers and step',dialog().textContent.includes('Шаг 3 из 5')&&dialog().querySelector('[value=outside_firebox]').checked)
 await click(dialog().querySelector('h2'));check('content click stays open',!!dialog())
 await act(async()=>dialog().dispatchEvent(new Event('pointerdown',{bubbles:true})));await click(dialog())
 check('backdrop closes and restores compact focus',!dialog()&&document.activeElement===compact)
 await click(compact)
 await act(async()=>dialog().dispatchEvent(new Event('cancel',{cancelable:true})))
 check('native cancel/Escape path closes',!dialog())
 await click(compact);await pick('year_round');await next()
 check('multi continue and progress80',dialog().querySelector('progress').value===80)
 await next();check('skip and progress100',dialog().querySelector('progress').value===100)
 check('empty timing stores skipped',JSON.parse(sessionStorage.getItem(data.QUIZ_STORAGE_KEY)).answers.quiz_timing==='skipped')
 await back();const timingGoals=stepGoals().length;await pick('month');await waitNext()
 check('timing auto advances once',dialog().textContent.includes('Шаг 5 из 5')&&stepGoals().length===timingGoals+1)
 await back();check('timing survives back',dialog().querySelector('[value=month]').checked)
 await next()
 const budgetGoals=stepGoals().length;await pick('350_500');await waitNext()
 check('budget auto advances to contacts once',!!dialog().querySelector('form')&&stepGoals().length===budgetGoals+1)
 await click(button('Назад к вопросам',dialog()));await pick('350_500')
 const fallbackGoals=stepGoals().length
 // Two events on the same live control before React commits must not advance twice.
 const forward=button('Далее',dialog())
 await act(async()=>{forward.dispatchEvent(new MouseEvent('click',{bubbles:true}));forward.dispatchEvent(new MouseEvent('click',{bubbles:true}))})
 await waitNext();check('Next racing with auto timer cannot double advance or double track',stepGoals().length===fallbackGoals+1&&JSON.parse(sessionStorage.getItem(data.QUIZ_STORAGE_KEY)).step===5)
 check('final form, no step HTTP requests',!!dialog().querySelector('form')&&payloads.length===0)
 check('final panel 640 and centered heading',dialog().firstElementChild.classList.contains('max-w-[640px]')&&dialog().querySelector('h2').classList.contains('text-center'))
 check('final CTA and return action retained',!!button('Получить подборку',dialog())&&!!button('Назад к вопросам',dialog()))
 await close();check('compact contact reminder remains available',!!button('Подобрать баню'))
 // Reminder remains compact after earlier collapse; section CTA also resumes final form.
 await click(button('Начать подбор'));check('final resume stays at contacts',!!dialog().querySelector('form'))
 await submit();check('phone method consent required',dialog().textContent.includes('Введите номер полностью')&&dialog().textContent.includes('Выберите способ связи')&&dialog().textContent.includes('Нужно согласие')&&payloads.length===0)
 const storageBeforeReturn=JSON.stringify([Object.entries(sessionStorage),Object.entries(window.localStorage)])
 await input(dialog().querySelector('[type=tel]'),'+79991234567');await submit();check('method still required',payloads.length===0)
 await pick('telegram');await submit();check('consent still required',payloads.length===0)
 await input(dialog().querySelector('[autocomplete=name]'),'Тест квиза');await click(dialog().querySelector('[type=checkbox]'))
 const enteredPhone=dialog().querySelector('[type=tel]').value
 await click(button('Назад к вопросам',dialog()))
 check('contacts Back opens last question without sending',dialog().textContent.includes('Шаг 5 из 5')&&!dialog().querySelector('form')&&payloads.length===0)
 await next()
 check('contact draft survives Back then Next',dialog().querySelector('[type=tel]').value===enteredPhone&&dialog().querySelector('[autocomplete=name]').value==='Тест квиза'&&dialog().querySelector('[value=telegram]').checked&&dialog().querySelector('[type=checkbox]').checked)
 check('contact navigation does not persist data in either storage',JSON.stringify([Object.entries(sessionStorage),Object.entries(window.localStorage)])===storageBeforeReturn)
 check('contact draft never enters goal parameters',goals.every(g=>Object.keys(g.params||{}).every(k=>['source','step','question'].includes(k)))&&!JSON.stringify(goals).includes('Тест квиза')&&!JSON.stringify(goals).includes('999123')&&!JSON.stringify(goals).includes('telegram'))
 const realNow=Date.now;Date.now=()=>realNow()+4000
 await submit();await submit();check('one pending request only',payloads.length===1&&dialog().querySelector('[type=submit]').disabled)
 check('flat stable payload',payloads[0].form==='quiz'&&payloads[0].quiz_version==='v1'&&payloads[0].quiz_features==='year_round,outside_firebox'&&payloads[0].quiz_timing==='month'&&payloads[0].quiz_area==='medium_45'&&payloads[0].quiz_budget==='350_500'&&payloads[0].contact_method==='telegram'&&Object.values(payloads[0]).every(v=>typeof v==='string'||typeof v==='number'))
 check('metadata and normalized phone',payloads[0].phone==='+79991234567'&&payloads[0].utm_source==='yandex'&&payloads[0].page_url&&'referrer' in payloads[0])
 check('storage has no contacts',!sessionStorage.getItem(data.QUIZ_STORAGE_KEY).includes('999123')&&!sessionStorage.getItem(data.QUIZ_STORAGE_KEY).includes('Тест квиза'))
 await act(async()=>resolveRequest({ok:false,status:500,json:async()=>({ok:false})}));check('error retains input, no success goal',!!dialog().querySelector('[role=alert]')&&dialog().querySelector('[type=tel]').value.includes('999')&&!goals.some(e=>e.goal==='quiz_submit'))
 await submit();check('manual retry only',payloads.length===2)
 await close();check('can close while request pending',!dialog())
 await click(button('Подобрать баню'))
 check('pending request remains locked after reopen',dialog().querySelector('[type=submit]').disabled&&button('Назад к вопросам',dialog()).closest('fieldset').disabled)
 await submit();check('reopen does not start a second pending request',payloads.length===2)
 await close()
 await act(async()=>resolveRequest({ok:true,status:200,json:async()=>({ok:true})}))
 check('success after closing suppresses reminder',!document.querySelector('aside'))
 check('submit goal once after ok',goals.filter(e=>e.goal==='quiz_submit').length===1)
 const saved=JSON.parse(sessionStorage.getItem(data.QUIZ_STORAGE_KEY));check('completion clears answers',saved.completed&&Object.keys(saved.answers).length===0)
 await unmount();await mount();check('completed restoration no reminder',!document.querySelector('aside')&&!dialog())
 await click(button('Начать подбор'));check('explicit restart begins step1',dialog().textContent.includes('Шаг 1 из 5'))
 await pick('no_plot');await close();await waitNext();await click(button('Продолжить',document.querySelector('aside')))
 check('closing cancels pending advance',dialog().textContent.includes('Шаг 1 из 5'))
 await pick('no_plot');await waitNext();await next();await next();await next();await next()
 const skipAnswers=JSON.parse(sessionStorage.getItem(data.QUIZ_STORAGE_KEY)).answers
 check('all four optional fields can be skipped',data.QUIZ_QUESTIONS.slice(1).every(q=>skipAnswers[q.field]==='skipped'))
 await close();check('contact reminder status, no step6',document.querySelector('aside').textContent.includes('Осталось оставить контакты')&&!document.querySelector('aside').textContent.includes('6 из 5'))
 const beforeResume=stepGoals().length;await click(button('Продолжить',document.querySelector('aside')))
 check('reminder Next opens contacts without extra step event',!!dialog().querySelector('form')&&stepGoals().length===beforeResume)
 check('new attempt has empty contact draft',dialog().querySelector('[type=tel]').value===''&&dialog().querySelector('[autocomplete=name]').value===''&&!dialog().querySelector('[type=radio]:checked')&&!dialog().querySelector('[type=checkbox]').checked)
 await input(dialog().querySelector('[type=tel]'),'+79991234567');await pick('call');await click(dialog().querySelector('[type=checkbox]'));Date.now=()=>realNow()+8000;await submit();check('explicit new run can submit once',payloads.length===3)
 await act(async()=>resolveRequest({ok:true,status:200,json:async()=>({ok:true})}))
 check('positive success state and centered title',dialog().querySelector('[role=status]')?.textContent===data.QUIZ_SUCCESS&&dialog().querySelector('h2').textContent===data.QUIZ_SUCCESS_TITLE&&dialog().querySelector('[role=status]').classList.contains('text-center'))
 check('quiz_start once per session despite explicit restart',goals.filter(e=>e.goal==='quiz_start').length===1)
 check('all opening sources tracked',['section','floating','compact'].every(source=>goals.some(g=>g.goal==='quiz_open'&&g.params.source===source)))
 check('goals contain no PII',goals.every(g=>Object.keys(g.params||{}).every(k=>['source','step','question'].includes(k)))&&!JSON.stringify(goals).includes('999123')&&!JSON.stringify(goals).includes('Тест квиза'))
 Date.now=realNow
 await unmount()
 sessionStorage.setItem(data.QUIZ_STORAGE_KEY,'{bad');check('bad storage fallback',data.readQuizState().step===0)
 sessionStorage.setItem(data.QUIZ_STORAGE_KEY,JSON.stringify({version:'v1',step:5,answers:{quiz_place:'fake'},widget:'expanded'}));check('invalid restored answers cannot bypass mandatory step',data.readQuizState().step===0)
 const app=await readFile(repo+'src/App.jsx','utf8');check('section order',app.indexOf('<SectionReviews />')<app.indexOf('<QuizSection />')&&app.indexOf('<QuizSection />')<app.indexOf('<SectionLocations />')&&app.indexOf('<SectionLocations />')<app.indexOf('<SectionCalculator />'))
 console.log(`Quiz DOM: ${checks} checks passed. Mock HTTP / polyfilled dialog, not browser layout QA.`)
} finally { await rm(folder,{recursive:true,force:true});dom.window.close() }
