// Run with jsdom installed outside production dependencies:
// BV_JSDOM_PATH=/absolute/path/to/jsdom/lib/api.js node scripts/tests/quiz.dom.mjs
import { build } from 'esbuild'
import { mkdir, rm, readFile } from 'node:fs/promises'
import { fileURLToPath, pathToFileURL } from 'node:url'
import assert from 'node:assert/strict'
const repo=fileURLToPath(new URL('../../',import.meta.url))
const { JSDOM }=await import(process.env.BV_JSDOM_PATH || 'jsdom')
const dom=new JSDOM('<div id="root"></div>',{url:'https://banivyatki.ru/?utm_source=yandex&utm_medium=cpc',pretendToBeVisual:true})
for(const k of ['window','document','sessionStorage','HTMLElement','HTMLInputElement','HTMLDialogElement','Event','MouseEvent','KeyboardEvent'])globalThis[k]=dom.window[k]
globalThis.IS_REACT_ACT_ENVIRONMENT=true
HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','')}
HTMLDialogElement.prototype.close=function(){this.removeAttribute('open')}
const folder=repo+'node_modules/.cache/quiz-dom';await mkdir(folder,{recursive:true})
await build({entryPoints:[repo+'src/components/quiz/QuizSection.jsx'],outfile:folder+'/quiz.mjs',bundle:true,format:'esm',platform:'node',jsx:'automatic',external:['react','react-dom','react/jsx-runtime'],define:{'import.meta.env.DEV':'false','import.meta.env.BASE_URL':'"/"'}})
const {default:React,act}=await import('react')
const {createRoot}=await import('react-dom/client')
const {default:Quiz}=await import(pathToFileURL(folder+'/quiz.mjs'))
const data=await import('../../src/data/quiz.js')
let root,checks=0,payloads=[],resolveRequest;const goals=[]
window.ym=(id,method,goal,params)=>goals.push({goal,params})
globalThis.fetch=async(url,options)=>{payloads.push(JSON.parse(options.body));return new Promise(r=>resolveRequest=r)}
const check=(label,value)=>{assert.ok(value,label);checks++}
const click=async(el)=>{assert.ok(el,'click target exists');await act(async()=>el.dispatchEvent(new MouseEvent('click',{bubbles:true})))}
const dialog=()=>document.querySelector('dialog[open]')
const button=(text,within=document)=>[...within.querySelectorAll('button')].find(e=>e.textContent===text)
const pick=async(code)=>click(dialog().querySelector(`input[value="${code}"]`))
const waitNext=()=>act(async()=>new Promise(r=>setTimeout(r,280)))
const mount=async()=>{root=createRoot(document.getElementById('root'));await act(async()=>root.render(React.createElement(React.StrictMode,null,React.createElement(Quiz))))}
const unmount=()=>act(async()=>root.unmount())
const close=()=>click(dialog().querySelector('[aria-label="Закрыть"]'))
const input=async(el,value)=>act(async()=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(el,value);el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}))})
const submit=()=>act(async()=>dialog().querySelector('form').dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})))
try {
 await mount()
 check('no automatic modal or reminder',!dialog()&&!document.querySelector('aside'))
 const launch=button('Начать подбор');launch.focus();await click(launch)
 check('banner opens native dialog and locks body',!!dialog()&&document.body.style.overflow==='hidden')
 check('step1 mandatory no skip',!button('Пропустить',dialog()))
 check('step1 progress20',dialog().querySelector('progress').value===20)
 await pick('ready');check('selected before advance',dialog().querySelector('[value=ready]').checked)
 await waitNext();check('single auto advances',dialog().textContent.includes('Шаг 2 из 5'))
 check('quiz_start only once',goals.filter(e=>e.goal==='quiz_start').length===1)
 await click(button('Назад',dialog()));check('back preserves selection',dialog().querySelector('[value=ready]').checked)
 await pick('ready');await waitNext();await pick('medium_45');await waitNext()
 await pick('year_round');await pick('terrace')
 check('multi does not auto advance',dialog().textContent.includes('Шаг 3 из 5'))
 check('multi selection',dialog().querySelectorAll('input:checked').length===2)
 await pick('unsure');check('unsure exclusive',dialog().querySelectorAll('input:checked').length===1&&dialog().querySelector('[value=unsure]').checked)
 await pick('outside_firebox');check('normal clears unsure',!dialog().querySelector('[value=unsure]').checked)
 await close();check('close returns focus and restores scroll',!dialog()&&document.activeElement===launch&&document.body.style.overflow==='')
 check('floating shown',!!button('Продолжить',document.querySelector('aside')))
 const floating=button('Продолжить',document.querySelector('aside'));floating.focus();await click(floating)
 check('resume step3 and answer',dialog().textContent.includes('Шаг 3 из 5')&&dialog().querySelector('[value=outside_firebox]').checked)
 await close();check('floating opener gets focus',document.activeElement===floating)
 await click(document.querySelector('[aria-label="Свернуть напоминание"]'))
 check('compact pill',!!button('Подобрать баню')&&!button('Продолжить',document.querySelector('aside')))
 await unmount();await mount();check('storage restores compact widget',!!button('Подобрать баню'))
 const compact=button('Подобрать баню');compact.focus();await click(compact)
 check('storage restores answers and step',dialog().textContent.includes('Шаг 3 из 5')&&dialog().querySelector('[value=outside_firebox]').checked)
 await click(dialog().querySelector('h2'));check('content click stays open',!!dialog())
 await act(async()=>dialog().dispatchEvent(new Event('pointerdown',{bubbles:true})));await click(dialog())
 check('backdrop closes and restores compact focus',!dialog()&&document.activeElement===compact)
 await click(compact)
 await act(async()=>dialog().dispatchEvent(new Event('cancel',{cancelable:true})))
 check('native cancel/Escape path closes',!dialog())
 await click(compact);await pick('year_round');await click(button('Продолжить',dialog()))
 check('multi continue and progress80',dialog().querySelector('progress').value===80)
 await click(button('Пропустить',dialog()));check('skip and progress100',dialog().querySelector('progress').value===100)
 await pick('350_500');await waitNext()
 check('final form, no step HTTP requests',!!dialog().querySelector('form')&&payloads.length===0)
 await submit();check('phone method consent required',dialog().textContent.includes('Введите номер полностью')&&dialog().textContent.includes('Выберите способ связи')&&dialog().textContent.includes('Нужно согласие')&&payloads.length===0)
 await input(dialog().querySelector('[type=tel]'),'+79991234567');await submit();check('method still required',payloads.length===0)
 await pick('telegram');await submit();check('consent still required',payloads.length===0)
 await input(dialog().querySelector('[autocomplete=name]'),'Тест квиза');await click(dialog().querySelector('[type=checkbox]'))
 const realNow=Date.now;Date.now=()=>realNow()+4000
 await submit();await submit();check('one pending request only',payloads.length===1&&dialog().querySelector('[type=submit]').disabled)
 check('flat stable payload',payloads[0].form==='quiz'&&payloads[0].quiz_version==='v1'&&payloads[0].quiz_features==='year_round,outside_firebox'&&payloads[0].quiz_timing==='skipped'&&payloads[0].contact_method==='telegram'&&Object.values(payloads[0]).every(v=>typeof v==='string'||typeof v==='number'))
 check('metadata and normalized phone',payloads[0].phone==='+79991234567'&&payloads[0].utm_source==='yandex'&&payloads[0].page_url&&'referrer' in payloads[0])
 check('storage has no contacts',!sessionStorage.getItem(data.QUIZ_STORAGE_KEY).includes('999123')&&!sessionStorage.getItem(data.QUIZ_STORAGE_KEY).includes('Тест квиза'))
 await act(async()=>resolveRequest({ok:false,status:500,json:async()=>({ok:false})}));check('error retains input, no success goal',!!dialog().querySelector('[role=alert]')&&dialog().querySelector('[type=tel]').value.includes('999')&&!goals.some(e=>e.goal==='quiz_submit'))
 await submit();check('manual retry only',payloads.length===2)
 await close();check('can close while request pending',!dialog())
 await act(async()=>resolveRequest({ok:true,status:200,json:async()=>({ok:true})}))
 check('success after closing suppresses reminder',!document.querySelector('aside'))
 check('submit goal once after ok',goals.filter(e=>e.goal==='quiz_submit').length===1)
 const saved=JSON.parse(sessionStorage.getItem(data.QUIZ_STORAGE_KEY));check('completion clears answers',saved.completed&&Object.keys(saved.answers).length===0)
 await unmount();await mount();check('completed restoration no reminder',!document.querySelector('aside')&&!dialog())
 await click(button('Начать подбор'));check('explicit restart begins step1',dialog().textContent.includes('Шаг 1 из 5'))
 await pick('no_plot');await close();await waitNext();await click(button('Продолжить',document.querySelector('aside')))
 check('closing cancels pending advance',dialog().textContent.includes('Шаг 1 из 5'))
 await pick('no_plot');await waitNext();await click(button('Пропустить',dialog()));await click(button('Пропустить',dialog()));await click(button('Пропустить',dialog()));await click(button('Пропустить',dialog()))
 await input(dialog().querySelector('[type=tel]'),'+79991234567');await pick('call');await click(dialog().querySelector('[type=checkbox]'));Date.now=()=>realNow()+8000;await submit();check('explicit new run can submit once',payloads.length===3)
 await act(async()=>resolveRequest({ok:true,status:200,json:async()=>({ok:true})}))
 check('visible success state',dialog().querySelector('[role=status]')?.textContent===data.QUIZ_SUCCESS)
 check('quiz_start once per session despite explicit restart',goals.filter(e=>e.goal==='quiz_start').length===1)
 check('all opening sources tracked',['section','floating','compact'].every(source=>goals.some(g=>g.goal==='quiz_open'&&g.params.source===source)))
 check('goals contain no PII',goals.every(g=>Object.keys(g.params||{}).every(k=>['source','step','question'].includes(k)))&&!JSON.stringify(goals).includes('999123')&&!JSON.stringify(goals).includes('Тест квиза'))
 Date.now=realNow
 await unmount()
 sessionStorage.setItem(data.QUIZ_STORAGE_KEY,'{bad');check('bad storage fallback',data.readQuizState().step===0)
 sessionStorage.setItem(data.QUIZ_STORAGE_KEY,JSON.stringify({version:'v1',step:5,answers:{quiz_place:'fake'},widget:'expanded'}));check('invalid restored answers cannot bypass mandatory step',data.readQuizState().step===0)
 const app=await readFile(repo+'src/App.jsx','utf8');check('section order',app.indexOf('<SectionReviews />')<app.indexOf('<QuizSection />')&&app.indexOf('<QuizSection />')<app.indexOf('<SectionLocations />')&&app.indexOf('<SectionLocations />')<app.indexOf('<SectionCalculator />'))
 console.log(`Quiz DOM: ${checks} checks passed. Mock HTTP / polyfilled dialog, not browser layout QA.`)
} finally { await rm(folder,{recursive:true,force:true});dom.window.close() }
